### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by OptumCS** [tanaikech/goris#1]
When doing a search like this: 
goris s -u https://images-na.ssl-images-amazon.com/images/M/MV5BMTk3ODYxNjQ3OV5BMl5BanBnXkFtZTgwNzA1MDQ5MTI@._V1_SX300.jpg -n 10

It throws an index out of range.  If you limit the result set to 9 with -n 9, it returns fine.  I think if the number of results returned is less than requested, it tries to loop beyond the index in dispres.  

I have zero experience in Go programming -- maybe a good opportunity to dig in and learn.
Thanks for a great utility ! ! !

**Comment by tanaikech** [comment]
Thank you very much for your report. I have never noticed it. I'm sorry.

Now I report that I could remove the error. Please confirm it.

For ``dispres()`` in goris.go, following script was added.

~~~golang
if len(r) < c {
	c = len(r)
}
~~~

**Comment by tanaikech** [comment]
Thank you very much for your report. I have never noticed it. I'm sorry.

Now I report that I could remove the error. Please confirm it.

For ``dispres()`` in goris.go, following script was added.

~~~golang
if len(r) < c {
	c = len(r)
}
~~~

**Comment by OptumCS** [comment]
Awesome!  Tested and works as expected.
Thanks for the quick response.

**Comment by tanaikech** [comment]
Thank you, too.

**Comment by Jackustc** [comment]
I downloaded goris and run the code in server and throws me 'a
-bash: goris: command not found
'. Does anyone know why?
Thanks!
