### ISSUE TITLE
Search for larger/highres versions of an image

### ISSUE THREAD

**Issue by bentolor** [tanaikech/goris#2]
Hi @tanaikech! This tools seems to be more or less exactly what I'm looking for.

I've got folder with hundreds of images scraped from a no longer existing image blog and would like to search&replace the mostly lowres pictures with higher resolution images that can be found on the net.

Unfortunately, Google, and hence `gores` seems to distinguish between normal "reverse image search" an larger copies. So a reverse search seems to provide everything _except_ the larger versions.

Is there something in the API which could i.e. be toggled by a command line argument to switch over to the larger version search?

Thanks!

**Comment by tanaikech** [comment]
Thank you for your comment. Unfortunately, this application and library are not use the API. And in this method, I couldn't find the method for selecting the resolution of images. This is due to my poor skill. I deeply apologize for this.

**Comment by bentolor** [comment]
Thank you, @tanaikech for your quick feedback! No reason to apologize: I didn't have a look in the code and assumed goris is using some sort of API. 

I highly doubt the problem is due to any missing skills: Even in interactive mode it is rather cumbersome now to navigate to the "other sizes" results.

Again, thank you very much for publishing this awesome, little tool and your kind help!

**Comment by tanaikech** [comment]
Thank you for replying. From your proposal, I also thought that such endpoint might be able to find. But, I couldn't find it. So when I could find the method and workaround for achieving your goal, I would like to implement it. Thank you for your proposal.
